# -*- coding: utf-8 -*-
"""app-mqtt.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VmHc9wDJpdOdEoayLcMqu6SXTWBqI88
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

nome_arquivo = list(uploaded.keys())[0]
df = pd.read_csv(nome_arquivo)

print("Colunas:", df.columns)

df['timestamp'] = pd.to_datetime(df['Timestamp'])

df = df.drop(columns=['Timestamp'])

df = df.sort_values(by='timestamp')

media_temp = df['Temperatura'].mean()
mediana_temp = df['Temperatura'].median()
moda_temp = df['Temperatura'].mode()[0]
desvio_temp = df['Temperatura'].std()

media_umid = df['Umidade'].mean()
mediana_umid = df['Umidade'].median()
moda_umid = df['Umidade'].mode()[0]
desvio_umid = df['Umidade'].std()

print("\nTemperatura:")
print(f"Média: {media_temp:.2f}")
print(f"Mediana: {mediana_temp:.2f}")
print(f"Moda: {moda_temp:.2f}")
print(f"Desvio padrão: {desvio_temp:.2f}")

print("\nUmidade:")
print(f"Média: {media_umid:.2f}")
print(f"Mediana: {mediana_umid:.2f}")
print(f"Moda: {moda_umid:.2f}")
print(f"Desvio padrão: {desvio_umid:.2f}")

plt.figure()

plt.plot(df['timestamp'], df['Temperatura'], marker='o', label='Temperatura')
plt.plot(df['timestamp'], df['Umidade'], marker='o', label='Umidade')

plt.axhline(media_temp, linestyle='--', label=f'Média Temp ({media_temp:.2f})')
plt.axhline(media_umid, linestyle=':', label=f'Média Umid ({media_umid:.2f})')

plt.title("Tendência de Temperatura e Umidade")
plt.xlabel("Tempo")
plt.ylabel("Valores")
plt.xticks(rotation=45)
plt.legend()

plt.tight_layout()
plt.show()